
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-27T15:26:57+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbb0c5a540a0ba91cb4dd20684bb00692305d193",
 "version": "1.0.0+fancy.166.gcbb0c5a"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
